### ISSUE TITLE
Please rewrite the documentation / Readme

### ISSUE THREAD

**Issue by klgrube** [GrafGenerator/ssrs-formularize#2]
I understand English may not be your native language, but I can't even begin to understand the Read me for what should be a terrific extension for SSRS.  I really don't know what to do.

My suggestion is that you ask someone here at github or a U.S. based colleague to help rewrite the documentation.

In the meantime, I'm going to try to get through this, as frustrating as it will be.  I hope it does what I need it to do.

**Comment by GrafGenerator** [comment]
Never faced such kind of issues even communicating with English natives. If you can point me to what parts are not clear, we can elaborate further and improve this documentation. Or probably you just need more context knowledge to get through this and nothing's wrong with the documentation.

BTW, if you find this documentation so frustrating, why not improve it by yourself and make a PR, huh?:smirk:

**Comment by klgrube** [comment]
HI!
I'm genuinely sorry if I seemed rude.  Honestly, I am frustrated and angry that SSRS doesn't do this natively. I've been struggling with this for about a week now, and I'm not getting much else done that my team needs.
I think one good idea might be to include some screenshots of an ssrs report design screen showing the formulas you have to build and how each formula winds up in Excel once it's exported.
A simple, sample SSRS report with perhaps a couple levels of group summaries might help too, one with maybe an excel data source that you can provide where someone can actually see the data going in, displayed in the report, and then exported to an final Excel file.
Here's one paragraph that I simply cannot interpret.


Report item anchor can be variable string, it can be programmatically generated since you free to provide any string you want to the function (expression is code, all is up to user).

 I just don't understand what you mean here, and I've been working with SSRS and even SSRS functions for years.
At the moment, I do think screen shots of an SSRS design screen showing expressions, etc. to accompany the documentation, along with a simple sample source data Excel file and an SSRS RDL file would help a great deal.  It doesn't have to be much.  Just a handful of columns with a couple of grouping levels would probably do it.  The Excel source can contain perhaps 20 -25 records but with at least two columns to group by . . .
StoreName   RegionName    DivisionName    JanSales    FebSales
Just put in about 20-25 rows where the report can group by RegionName then by DivisionName Totaling the Sales figures.
Then create a simple SSRS report showing this information and what it would look like using formularize formulas.
That's just a thought.
In the meantime, I'm still unable to create an ssrs report based on what the documentation shows.  I don't even know where to begin.
Thank you so much for responding!  I truly appreciate it.  I hope this helps!
Karen

    On Saturday, October 5, 2019, 08:15:39 PM PDT, Nikita Ivanov <notifications@github.com> wrote:  
 
 
Never faced such kind of issues even communicating with English natives. If you can point me to what parts are not clear, we can elaborate further and improve this documentation. Or probably you just need more context knowledge to get through this and nothing's wrong with the documentation.

BTW, if you find this documentation so frustrating, why not improve it by yourself and make a PR, huh? 😏

**Comment by GrafGenerator** [comment]
Hey!
No problem at all, again I think it's just lack of context knowledge for you. There's at least one who was able to use this extension using the documentation I wrote. Although it may be good idea to attach some screenshots and/or example report to showcase usage scenarios, it requires some effort from me which I can't do in near future. Lets try to get with your issues by explaining first, and then I will create separate issue for adding screenshots/ examples/etc.

To understand what I mean, I need to say thing that you sure do know: the report item can produce many instances of itself when the report layout gets populated with the data from the datasource. The simplest example is a table with details row - each details row's cell is a text box itself (report item, say TextBox1), when populating this table with the data there will be many rows, each will have own instance of TextBox1 with it's own value, corresponding to the data from the datasource. Obviously, without the ability to distinguish this instances my extension wouldn't be useful, no one wants to reference static cells. That's why this report item instances must be referenced in some distinguishable way. I use Action link for this as it's the only one report item property that goes unchanged through the internals of SSRS:)
 
I generate special encoded value, containing the formula for this cell, written in DSL, and an anchor - a reference, you can think of it as a moniker, an alias, whatever makes more sense for you. In terms of Formularizer anchor is string value, preferably unique, which you can use to certainly define the scope of cells for your Excel formula.
The sentence you're quoted saying that you (obviously) can generate this anchor (string) programmatically using expression, thus distinguishing each report item instance. In case of that textbox, you can set it to be 
```vb
=code.EncodeFormula(
    "txt1_row" & Fields!UniqueRowID, ' <=== we're creating unique string anchor assuming we have some unique ID in the dataset, usually we do have it 
    ""  ' <=== no formula here 
)
```
All alone this will produce nothing in the exporte report. But not each cell, produced by that TextBox1 report item can be uniquely requested by anchors "txt1_row1", "txt1_row2", "txt1_row3", etc assuming we have 1,2,3,... as rows IDs in the dataset. 

Imagine that next textbox in that row, TextBox2, has this:
```vb
=code.EncodeFormula(
    "", ' <=== no anchor, we're not referencing this cells 
    "{cell 'txt1_row" & Fields!UniqueRowID & "' row} + 1"  ' <=== increment by 1
)
```

This textbox will produce formulas in excel increment by 1 the value from cells, referenced as txt1_rowN. To understand further explanation, consider that all formulas processing done on the Excel file (!) generated by SSRS. It just has the info attached to cells as hyperlink, which then will be removed.
So, returning to that formula, Formularizer will process all inside {...}, thinking of it as of formula. ```cell 'txt1_row" & Fields!UniqueRowID & " row``` says it to take first cell in current row with anchor "txt1_row1", "txt1_row2", "txt1_row3", etc. Current row means the row where resides instance of TextBox2, because there is the formula which Formularizer processes at the moment. Obviously there can be many of such rows, 20, 25, 1000, your number).
Since we're using ID again, this cell will get corresponding Excel formulas: =B1+1, =B2+1, =B3+1, ... .

From this point you can extrapolate this idea and built as complex formulas as you want, however I have to say it's hard. If you have some troubles with formulas, extension should output error to resulting document.

P.S. Anchor is preferred to be unique, but not always - if you want to reference whole column (say A:A), you can use not unique anchor for textbox, say "lalala", and then formula for column will take first cell found and build formula for it. See DSL spec for more info.

**Comment by GrafGenerator** [comment]
Hi @klgrube, were you able to get it working?
